meta_product_name: "Homeboard"
meta_title: "homeboard - Live better together"
meta_description: "Manage your life resident and live better with your neighbors"
meta_image: "cover.jpg" # devrait exister dans `app / assets / images /`
